import assert from "node:assert/strict";
import path from "node:path";
export async function testLayouts(page, openPalette, report, output) {
  const passed = test => report.cases.push({ test, result: "passed" });
  const model = await page.evaluate(() => {
    const api = window.layoutTest;
    const initial = api.defaultLayout({ tabPosition: "right", inboxOpen: false });
    const chat = api.panes(initial.root).find(p => p.panel === "chat");
    const checks = [];
    for (const platform of api.PLATFORMS) for (const side of ["left", "right", "top", "bottom"]) {
      const split = api.dock(initial, { paneId: chat.id, platform }, chat.id, side);
      const leaves = api.panes(split.root), solo = leaves.find(p => p.platforms.length === 1), group = leaves.find(p => p.platforms.length === 2);
      const combined = api.dock(split, { paneId: solo.id }, group.id, "center");
      checks.push(!!api.validateLayout(split) && leaves.filter(p => p.panel === "chat").length === 2 && api.panes(combined.root).filter(p => p.panel === "chat").length === 1);
    }
    let nested = api.dock(initial, { paneId: chat.id, platform: "youtube" }, chat.id, "bottom");
    nested = api.dock(nested, { paneId: chat.id, platform: "kick" }, chat.id, "right");
    nested = api.resize(nested, nested.root.id, .3);
    const restored = api.validateLayout(JSON.parse(JSON.stringify(nested)));
    const shown = api.showInbox(nested, true), hidden = api.showInbox(shown, false);
    const corrupt = structuredClone(initial);
    api.panes(corrupt.root).find(p => p.panel === "chat").platforms = ["twitch", "twitch", "youtube"];
    const invalidRatio = structuredClone(initial); invalidRatio.root.ratio = 2;
    const fallback = window.profilesTest.loadProfiles({ version: 1, profiles: [{ id: "normal", layout: corrupt }] }, { fontSize: 13, tabSize: "compact", tabPosition: "right", inboxOpen: false });
    return { valid: !!api.validateLayout(initial), checks, nested: api.panes(restored.root).map(p => p.platforms), ratio: restored.root.ratio, hidden: api.panes(hidden.root).map(p => p.panel), shown: api.panes(shown.root).map(p => p.panel), corrupt: api.validateLayout(corrupt), invalidRatio: api.validateLayout(invalidRatio), fallback: fallback.profiles[0].layout };
  });
  assert.equal(model.valid, true); assert.equal(model.checks.length, 12); assert.ok(model.checks.every(Boolean));
  passed("layout model: combined default, each platform separates on all four edges and recombines without duplicates");
  assert.deepEqual(model.nested.flat().sort(), ["kick", "twitch", "youtube"]); assert.equal(model.nested.filter(p => p.length).length, 3); assert.equal(model.ratio, .3);
  assert.ok(model.shown.includes("inbox")); assert.ok(!model.hidden.includes("inbox")); assert.ok(model.hidden.includes("channels"));
  assert.equal(model.corrupt, null); assert.equal(model.invalidRatio, null); assert.equal(model.fallback, null);
  passed("nested three-way layout, horizontal/vertical splits, ratio serialization, visibility and corrupt-layout fallback");
  const store = () => page.evaluate(() => JSON.parse(localStorage.getItem("fyflate.profiles.v1")));
  const before = await store();
  const start = async () => { const q = await openPalette(); await q.getByRole("combobox").fill("Edit current layout"); await q.getByRole("option", { name: "Edit current layout", exact: true }).click(); await page.getByRole("region", { name: "Edit layout", exact: true }).waitFor(); };
  await page.setViewportSize({ width: 1200, height: 850 });
  await start();
  const editor = page.getByRole("region", { name: "Edit layout", exact: true });
  const combined = page.getByRole("region", { name: "Twitch + Kick + YouTube", exact: true });
  const youtube = combined.locator('[data-layout-platform="youtube"]');
  const youtubeBox = await youtube.boundingBox();
  await page.mouse.move(youtubeBox.x + youtubeBox.width / 2, youtubeBox.y + youtubeBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(youtubeBox.x + youtubeBox.width / 2 - 12, youtubeBox.y + youtubeBox.height / 2 + 8, { steps: 4 });
  const right = combined.locator('[data-drop-side="right"]');
  await right.waitFor();
  const rightBox = await right.boundingBox();
  await page.mouse.move(rightBox.x + rightBox.width / 2, rightBox.y + rightBox.height / 2, { steps: 5 });
  await page.screenshot({ path: path.join(output, "layout-drop-preview.png") });
  await page.mouse.up();
  await page.getByRole("region", { name: "Twitch + Kick", exact: true }).waitFor();
  await page.getByRole("region", { name: "YouTube", exact: true }).waitFor();
  await page.getByRole("separator").first().press("ArrowLeft");
  assert.deepEqual(await store(), before, "draft never persists before Save");
  await editor.getByRole("button", { name: "Undo", exact: true }).click();
  await editor.getByRole("button", { name: "Cancel", exact: true }).click();
  assert.deepEqual(await store(), before);
  assert.equal(await page.locator("[data-layout-workspace]").count(), 0);
  passed("drag/drop preview separates YouTube; keyboard resizing, bounded edit Undo and Cancel leave persisted profile untouched");
  await start();
  await editor.getByText("Move without dragging", { exact: true }).click();
  const move = async (source, target, position) => {
    await editor.getByRole("combobox", { name: "Move panel or platform" }).selectOption({ label: source });
    await editor.getByRole("combobox", { name: "Target pane" }).selectOption({ label: target });
    await editor.getByRole("combobox", { name: "Dock position" }).selectOption(position);
    await editor.getByRole("button", { name: "Move", exact: true }).click();
  };
  await move("youtube (Twitch + Kick + YouTube)", "Twitch + Kick + YouTube", "bottom");
  await move("kick (Twitch + Kick)", "Twitch + Kick", "right");
  assert.equal(await page.locator("[data-layout-platform]").count(), 3);
  await editor.getByRole("checkbox", { name: "Inbox", exact: true }).check();
  await page.getByRole("region", { name: "Inbox", exact: true }).waitFor();
  await editor.getByRole("checkbox", { name: "Inbox", exact: true }).uncheck();
  await editor.getByRole("checkbox", { name: "Inbox", exact: true }).check();
  await page.getByRole("separator").first().press("ArrowLeft");
  await page.screenshot({ path: path.join(output, "layout-three-panes.png") });
  await editor.getByRole("button", { name: "Save layout", exact: true }).click();
  const saved = (await store()).profiles.find(p => p.id === before.activeId).layout;
  assert.ok(saved);
  assert.equal(await page.getByRole("separator").count(), 0);
  assert.equal(await page.locator('[data-layout-platform][draggable="true"]').count(), 0);
  await page.locator('[data-tutorial-id="settings-button"]').waitFor();
  await page.locator('[data-channel-tab-id="cached:fixtureone"]').waitFor();
  passed("keyboard docking creates three panes; hidden Inbox restores; Save persists ratios and layout locks outside editing");
  await page.reload();
  await page.locator('[data-layout-workspace]').waitFor();
  assert.deepEqual((await store()).profiles.find(p => p.id === before.activeId).layout, saved);
  for (const command of ["Switch to Minimal", "Switch to Normal"]) { const q = await openPalette(); await q.getByRole("combobox").fill(command); await q.getByRole("option", { name: command, exact: true }).click(); }
  await page.locator('[data-layout-workspace]').waitFor();
  assert.deepEqual((await store()).profiles.find(p => p.id === "normal").layout, saved);
  await page.setViewportSize({ width: 460, height: 600 });
  await page.screenshot({ path: path.join(output, "layout-narrow.png") });
  assert.deepEqual((await store()).profiles.find(p => p.id === "normal").layout, saved);
  await page.setViewportSize({ width: 1200, height: 850 });
  await start();
  await editor.getByText("Move without dragging", { exact: true }).click();
  await move("Kick", "Twitch", "center");
  await page.getByRole("region", { name: "Twitch + Kick", exact: true }).waitFor();
  await editor.getByRole("button", { name: "Cancel", exact: true }).click();
  assert.deepEqual((await store()).profiles.find(p => p.id === "normal").layout, saved);
  passed("profile-specific layout survives restart/switch/resize; recombination reuses chat group and Cancel restores saved three-way arrangement");
  const q = await openPalette(); await q.getByRole("combobox").fill("Reset profile layout"); await q.getByRole("option", { name: "Reset profile layout…", exact: true }).click();
  assert.deepEqual((await store()).profiles.find(p => p.id === "normal").layout, saved);
  await page.getByRole("button", { name: "Confirm layout reset", exact: true }).click();
  assert.equal((await store()).profiles.find(p => p.id === "normal").layout, null);
  assert.deepEqual((await store()).profiles.filter(p => p.id !== "normal"), before.profiles.filter(p => p.id !== "normal"));
  passed("reset command requires confirmation and only removes active profile layout");
  await page.setViewportSize({ width: 800, height: 600 });
  await page.reload(); await page.locator('[data-tutorial-id="settings-button"]').waitFor();
  const first = page.locator('[data-channel-tab-id="cached:fixtureone"]');
  const second = page.locator('[data-channel-tab-id="cached:fixturetwo"]');
  const firstBox = await first.boundingBox(), secondBox = await second.boundingBox();
  // Start from the broad center/right area, not the old six-pixel grip.
  await page.mouse.move(firstBox.x + firstBox.width * .75, firstBox.y + firstBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(secondBox.x + secondBox.width * .75, secondBox.y + secondBox.height * .2, { steps: 8 });
  await page.mouse.up();
  const order = await page.locator('[data-channel-tab-id]').evaluateAll(nodes => nodes.map(node => node.dataset.channelTabId));
  assert.ok(order.indexOf("cached:fixtureone") < order.indexOf("cached:fixturetwo"));
  passed("whole channel row pointer-drag reorders tabs without requiring the narrow left grip");
}
