import assert from "node:assert/strict";
import path from "node:path";
export async function testProfiles(page, openPalette, report, output) {
  const passed = test => report.cases.push({ test, result: "passed" });
  const migration = await page.evaluate(() => {
    const api = window.profilesTest;
    const current = { fontSize: 19, tabPosition: "bottom", tabSize: "normal", inboxOpen: false };
    const migrated = api.loadProfiles(null, current);
    const sanitized = api.loadProfiles({ ...migrated, profiles: [{ id: "normal", view: { ...current, token: "must-not-store", channels: ["bad"] } }] }, current);
    return { migrated, sanitized, current };
  });
  assert.deepEqual(migration.migrated.profiles[0].view, migration.current);
  assert.deepEqual(migration.sanitized.profiles.map(p => p.id), ["normal", "streamer", "moderator", "minimal"]);
  assert.deepEqual(Object.keys(migration.sanitized.profiles[0].view).sort(), ["fontSize", "inboxOpen", "tabPosition", "tabSize"]);
  passed("profile migration preserves current Normal; built-ins repaired; unallowlisted data stripped");
  const openProfiles = async () => {
    const quick = await openPalette();
    await quick.getByRole("combobox").fill("Open Profiles");
    await quick.getByRole("option", { name: "Open Profiles", exact: true }).click();
    const panel = page.getByRole("region", { name: "Profiles", exact: true });
    await panel.waitFor();
    return panel;
  };
  let panel = await openProfiles();
  const store = () => page.evaluate(() => JSON.parse(localStorage.getItem("fyflate.profiles.v1")));
  const original = await store();
  for (const name of ["Normal", "Streamer", "Moderator", "Minimal"]) {
    const card = panel.getByRole("article", { name, exact: true });
    assert.equal(await card.getByRole("button", { name: "Delete", exact: true }).count(), 0);
    assert.equal(await card.getByRole("button", { name: "Rename", exact: true }).count(), 0);
  }
  // Snapshot actual protected app keys, not dummy profile fields.
  const snapshot = () => page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([key]) => /token|oauth|account|channel|nickname|ignore|highlight|history|quota|obs|motion|contrast/i.test(key) && !/channelTabs|channelTabPosition|channelTabSize/i.test(key))));
  const before = await snapshot();
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption("minimal");
  await page.waitForFunction(() => JSON.parse(localStorage.getItem("fyflate.profiles.v1")).activeId === "minimal", null, { timeout: 5000 });
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  assert.equal((await store()).activeId, original.activeId);
  passed("built-in protection; immediate switching and existing Undo restore previous profile");
  await panel.getByRole("textbox", { name: "Profile name" }).fill("Laptop");
  await panel.getByRole("button", { name: "Create from current setup" }).click();
  const laptop = panel.getByRole("article", { name: "Laptop", exact: true });
  await laptop.waitFor();
  const customId = (await store()).profiles.find(p => p.name === "Laptop").id;
  await laptop.getByRole("button", { name: "Rename", exact: true }).click();
  await panel.getByRole("textbox", { name: "Profile name" }).fill("Gaming");
  await panel.getByRole("button", { name: "Save", exact: true }).click();
  assert.equal((await store()).profiles.find(p => p.name === "Gaming").id, customId);
  await panel.getByRole("article", { name: "Gaming", exact: true }).getByRole("button", { name: "Duplicate" }).click();
  await panel.getByRole("button", { name: "Save", exact: true }).click();
  await panel.getByRole("article", { name: "Gaming copy", exact: true }).waitFor();
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption(customId);
  await panel.getByRole("article", { name: "Gaming", exact: true }).getByRole("button", { name: "Delete", exact: true }).click();
  assert.equal((await store()).activeId, customId);
  await panel.getByRole("button", { name: "Confirm delete" }).click();
  assert.equal((await store()).activeId, "normal");
  assert.ok(!(await store()).profiles.some(p => p.id === customId));
  passed("custom create, stable rename, duplicate, delete confirmation and active deletion returns to Normal");
  const palette = await openPalette();
  await palette.getByRole("combobox").fill("Switch to Minimal");
  await palette.getByRole("option", { name: "Switch to Minimal", exact: true }).click();
  await page.reload();
  panel = await openProfiles();
  assert.equal(await panel.getByRole("combobox", { name: "Active profile" }).inputValue(), "minimal");
  assert.equal((await store()).profiles.some(p => p.name === "Gaming copy"), true);
  await page.locator('[data-tutorial-id="settings-button"]').waitFor();
  await page.locator('[data-channel-tab-id="cached:fixtureone"]').waitFor();
  await panel.getByRole("article", { name: "Minimal", exact: true }).getByRole("button", { name: "Reset", exact: true }).click();
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption("normal");
  assert.deepEqual(await snapshot(), before);
  await page.screenshot({ path: path.join(output, "profiles.png") });
  passed("Ctrl+K profile switching, restart persistence, reset, Minimal navigation and unchanged protected storage");
  // Existing controls update only the currently active profile.
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption("streamer");
  await page.locator('[aria-label="Settings pages"]').getByRole("button", { name: /Chat$/ }).click();
  const font = page.locator('[data-tutorial-id="settings-shell"] input[type="range"][min="10"][max="24"]');
  await font.fill("18");
  await page.waitForFunction(() => JSON.parse(localStorage.getItem("fyflate.profiles.v1")).profiles.find(p => p.id === "streamer").view.fontSize === 18, null, { timeout: 5000 });
  panel = await openProfiles();
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption("normal");
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption("streamer");
  assert.equal((await store()).profiles.find(p => p.id === "streamer").view.fontSize, 18);
  await page.reload();
  panel = await openProfiles();
  assert.equal((await store()).profiles.find(p => p.id === "streamer").view.fontSize, 18);
  await panel.getByRole("article", { name: "Streamer", exact: true }).getByRole("button", { name: "Reset", exact: true }).click();
  assert.equal((await store()).profiles.find(p => p.id === "streamer").view.fontSize, 15);
  await panel.getByRole("combobox", { name: "Active profile" }).selectOption("normal");
  assert.deepEqual((await store()).profiles.find(p => p.id === "normal").view, original.profiles.find(p => p.id === "normal").view);
  const search = page.getByRole("textbox", { name: "Search settings", exact: true });
  await search.fill("profiles");
  await page.locator('[data-tutorial-id="settings-shell"]').getByRole("button", { name: /Profiles.*Switch your view/ }).click();
  await page.getByRole("region", { name: "Profiles", exact: true }).waitFor();
  await page.keyboard.press("Control+Shift+f");
  const global = page.getByRole("dialog", { name: "Search FyFlade", exact: true });
  await global.waitFor();
  await global.getByRole("combobox", { name: "Search FyFlade", exact: true }).fill("streamer profile");
  await global.getByRole("option").filter({ hasText: "Profiles" }).first().click();
  assert.equal((await store()).activeId, "normal");
  passed("active-profile changes persist through switches/reload; reset is scoped; Settings and Global Search only navigate to Profiles");
  const detached = await page.context().newPage();
  detached.on("pageerror", error => report.errors.push(error.message));
  await detached.goto(`${page.url()}?fyflateWindow=settings`);
  await detached.locator('[aria-label="Settings pages"]').getByRole("button", { name: /Profiles$/ }).click();
  await detached.getByRole("combobox", { name: "Active profile" }).selectOption("moderator");
  await page.waitForFunction(() => document.querySelector('select[aria-label="Active profile"]')?.value === "moderator", null, { timeout: 5000 });
  await page.getByRole("combobox", { name: "Active profile" }).selectOption("normal");
  await detached.waitForFunction(() => document.querySelector('select[aria-label="Active profile"]')?.value === "normal", null, { timeout: 5000 });
  await detached.close();
  passed("profile switching synchronizes between main view and detached Settings without reopening");
  await page.getByRole("heading", { name: "Profiles", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(output, "profiles-top.png") });
  await page.setViewportSize({ width: 480, height: 620 });
  const bounds = await page.getByRole("region", { name: "Profiles", exact: true }).boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 480);
  assert.equal(await page.getByRole("region", { name: "Profiles", exact: true }).evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await page.screenshot({ path: path.join(output, "profiles-narrow.png") });
  await page.setViewportSize({ width: 800, height: 600 });
  await page.reload();
  await page.locator('[data-tutorial-id="settings-button"]').waitFor();
}
